name: Dotnet-CI

on:
  push:
    branches: [ "main" ]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build steps
        run: |
          echo "Starting build..."
          cd dotnetapp 
          dotnet restore
          dotnet build --configuration Release 
          dotnet publish -c Release -o output 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with: 
          name: dotnet-artifact.zip
          path: output/*    